# Generated by Django 2.0.6 on 2018-06-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssubscriber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='token',
            field=models.CharField(default='9lkf7I3CeA8zcuoJa2ylc99VJSv3gW5ClYOZ1TqI', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name'),
        ),
    ]
